### PR TITLE
Add no-changelog to be an additional label

### PR DESCRIPTION
**Pull request by LinuxSuRen**
/cc @zryfish

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
Hi @LinuxSuRen , I don't exactly know what the effect would be, could you explain this in detail?

**Comment by LinuxSuRen** [comment]
> Hi @LinuxSuRen , I don't exactly know what the effect would be, could you explain this in detail?

It can support adding a label `no-changelog` with the command `/label no-changelog`. Releaser Drafter can skip to add a changelog item. See also https://github.com/kubesphere/ks-devops/blob/9d3d5a6f4f37bba2087c5b8f6d9e1d7416b5c0bc/.github/release-drafter.yml#L39

**Comment by JohnNiang** [comment]
> It can support adding a label `no-changelog` with the command `/label no-changelog`. Releaser Drafter can skip to add a changelog item. See also https://github.com/kubesphere/ks-devops/blob/9d3d5a6f4f37bba2087c5b8f6d9e1d7416b5c0bc/.github/release-drafter.yml#L39

Make sense to me.
/lgtm

**Pull request closed without merging**
