### PR TITLE
Add milestone plugins for kubesphere/ks-devops repo

### PR DESCRIPTION
**Pull request by JohnNiang**
- milestone
- milestonestatus

### CODE REVIEW

**Comment by zryfish** [comment]
/lgtm
/approve

To add a milestone to an issue/PR, you also need to be member of milestone-maintainers https://github.com/orgs/kubesphere/teams/milestone-maintainers.

**Comment by JohnNiang** [comment]
@zryfish , thanks for reminding.

**Comment by JohnNiang** [comment]
@zryfish , please have a look at [here](https://github.com/kubesphere/ks-devops/issues/91). It looks like that `/milestone` dose not work.

**Pull request merged**
